Update composer.lock to update to PHPUnit 3.6.2.
This is done to fix the "Fatal error: Class undefined: PHP_Token_JOIN" error when code coverage reports are generated at the end of unit tests.